/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function getSubsetSum(list: Array<number>, sum: number, timeout?: number | undefined | null): Array<number> | undefined | null
