/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getSubsetSum(list: Array<number>, sum: number, timeout?: number | undefined | null): Array<number> | null
export declare function getAllSubsetSums(list: Array<number>, sum: number, timeout?: number | undefined | null): Array<Array<number>>
